const Schema = mongoose.Schema;

const bookies = [
  "Interwetten",
  "bwin",
  "bet-at-home",
  "Centrebet",
  "Unibet",
  "Betsson exch.",
  "Stan James",
  "Expekt",
  "PartyBets",
  "Gamebookers",
  "Canbet",
  "10Bet",
  "William Hill",
  "bet365",
  "Blue Square",
  "Pinnacle",
  "Sports Interaction",
  "5Dimes",
  "Betfred",
  "DOXXbet",
  "Betsafe",
  "Betway",
  "888sport",
  "Ladbrokes",
  "Sunmaker",
  "BoyleSports",
  "Everygame",
  "Betclic",
  "NordicBet",
  "Bodog",
  "Eurobet",
  "Sportingbet",
  "Betdaq",
  "Sportbet",
  "mybet",
  "Betsson",
  "Betfair Exchange",
  "Chance.cz",
  "iFortuna.cz",
  "MAXITIP.cz",
  "Tipsport.cz",
  "bwin.it",
  "Bet24",
  "Noxwin",
  "188BET",
  "Jetbull",
  "BetUS",
  "Paddy Power",
  "Sports Alive",
  "Internet1x2",
  "BetCRIS",
  "Bookmaker",
  "Tipico",
  "Coral",
  "bets4all",
  "Leonbets",
  "Skybet",
  "SBOBET",
  "BetVictor",
  "Players Only",
  "BetOnline",
  "BetDSI",
  "12BET",
  "betoto",
  "Heroes Sports",
  "Bet7days",
  "digibet",
  "Legends",
  "Sports-1",
  "BetGun",
  "BetPhoenix",
  "Island Casino",
  "The Greek",
  "Stryyke",
  "Superbahis",
  "World Sports Exchange",
  "Sportsbook",
  "Paf",
  "Redbet",
  "totepool",
  "betChronicle",
  "Betboo",
  "Sports",
  "Oddsmaker",
  "Betonline247",
  "Instant Action Sports",
  "Betinternet",
  "Betcruise",
  "Justbet",
  "Bet770",
  "Extrabet",
  "Goalwin",
  "Circlebet",
  "Titanbet",
  "EurosportBET",
  "Bet911",
  "Luxbet",
  "Bestbet",
  "Bestake",
  "youwin",
  "bwin.fr",
  "Tobet",
  "EurosportBET.fr",
  "SAjOO FR",
  "ParionsWeb.fr",
  "betWize",
  "BetBeast",
  "Bet Victor",
  "BetRedKings",
  "France Pari",
  "Betclic.it",
  "Betclic.fr",
  "Bets10",
  "Sportingbet.au",
  "Partybets.fr",
  "BetVictor.de",
  "AllYouBet",
  "Dafabet",
  "Interwetten.es",
  "LBapuestas",
  "Miapuesta",
  "Triobet",
  "PMU FR",
  "32Red Bet",
  "Totosi",
  "Getwin",
  "Unibet.it",
  "Sportsbet.com.au",
  "Sisal",
  "Unibet.fr",
  "NetBet",
  "STARLOTTOSPORT",
  "eFortuna.pl",
  "iFortuna.sk",
  "STS.pl",
  "Nike",
  "Teletip",
  "Totomix",
  "Tipos",
  "Milenium",
  "Betako",
  "WagerWeb",
  "Nike.sk",
  "SBG Global",
  "Eurobet.it",
  "Victory Tip",
  "Bet1128.it",
  "Globetsport",
  "Admiral",
  "ShilBet",
  "Kajot bet",
  "WilliamHill.it",
  "Top Bet",
  "Interapostas",
  "Interwetten.it",
  "FortunaWin",
  "Bovada",
  "TonyBet",
  "PaddyPower.it",
  "Offsidebet",
  "Marathonbet",
  "Forvetbet",
  "ComeOn",
  "bet-at-home.it",
  "SportsBettingOnline",
  "Ucabet",
  "SportsBetting",
  "90dakika",
  "Heaven Bet",
  "Matchbook",
  "WSBets",
  "bwin.es",
  "Oddsring",
  "Tipico.it",
  "Tempobet",
  "Oddset",
  "Winline",
  "NetBet.fr",
  "Winner",
  "HiperBet",
  "mybet.it",
  "Hepsibahis",
  "Betrally",
  "Seaniemac",
  "Bet9",
  "Sportium.es",
  "Vistabet.gr",
  "Sportingbet.gr",
  "Stoiximan.gr",
  "Dhoze",
  "Tipsport.sk",
  "BET2BE",
  "GoBetGo",
  "SAZKAbet.cz",
  "Dashbet",
  "18bet",
  "1xBet",
  "Vernons",
  "bet365.it",
  "WonOdds",
  "Betadonis",
  "5plusbet",
  "NetBet.it",
  "138",
  "RealDealBet",
  "OtoBet",
  "VitalBet",
  "Kroon Casino",
  "Betfair",
  "Winmasters",
  "SuperAposta",
  "Bettilt",
  "Guts",
  "Jojobet",
  "SportingbetMaster",
  "Bet-52",
  "BizimBahis",
  "Fortuna.ro",
  "Restbet",
  "Marcaapuestas",
  "Tipobet",
  "VonBets",
  "BetWorld",
  "Sekabet",
  "BetOlimp",
  "Betclic.pt",
  "Intragame",
  "betcart",
  "Grandbetting",
  "Vulkan Bet",
  "BetEast",
  "1xStavka.ru",
  "Winline.ru",
  "Leon.ru",
  "Riccobet",
  "Luckia.es",
  "BetolimpMaster",
  "bwin.pt",
  "Tipbet",
  "MrRingo",
  "iForBet.pl",
  "Tiplix",
  "Bethard",
  "Winmasters.ro",
  "Betebet",
  "Planetwin365",
  "Coolbet",
  "Babibet",
  "Marsbet",
  "1xBet.kz",
  "Totolotek.pl",
  "ScandiBet",
  "TestingOnly",
  "Betser",
  "Asianodds",
  "Betmoon",
  "Dotabet",
  "Mobilbahis",
  "Truvabet",
  "BetCity.ru",
  "BetCity",
  "Inkabet",
  "ParionsSport",
  "Smarkets",
  "OLIMPBET",
  "Betpas",
  "Bahis Arena",
  "Starvegas.it",
  "Bwin.dk",
  "Parimatch",
  "NightRush",
  "europebet",
  "efbet",
  "CasinoEstoril",
  "MarathonbetTest",
  "Ligastavok",
  "TippmixPro",
  "Betstars",
  "22Bet",
  "SportPesa.it",
  "LV BET",
  "Nairabet",
  "Sportimba",
  "Marsbahis",
  "Betfarm",
  "Betsafe.lv",
  "Betsafe.ee",
  "Bet9ja",
  "betin.ug",
  "betin.ke",
  "Betsafe.lt",
  "Supabets",
  "BetJoe",
  "Kwikbet.co.ke",
  "Betano.ro",
  "Profitbet",
  "SupabetsZA",
  "GSB.com.ug",
  "KTO",
  "Sportingbet.co.za",
  "WSB.co.za",
  "Wplay.co",
  "Zamba.co",
  "Betrally India",
  "Speedybet",
  "Parimatch.ru",
  "Snabbare",
  "Hajper",
  "Vivelasuerte",
  "Marathonbet.ru",
  "DoradoBet",
  "Betway Africa",
  "SuperSport",
  "MrGreen",
  "Betbiga",
  "1bet",
  "Parimatchtz",
  "Betclic.pl",
  "10cric",
  "Rushbet.co",
  "Fortebet",
  "Betago",
  "Betika",
  "Betano.pt",
  "Kirolbet",
  "Fonbet.kz",
  "Domusbet",
  "bet365.nj",
  "GGBET",
  "Luckia.pt",
  "BetAlfa.co",
  "Circus.pe",
  "Betfan.pl_old",
  "Toto.nederlandse",
  "BetjuegoOld",
  "Totonederlandse",
  "GGBET.ru",
  "X-bet.co",
  "Topaz.az",
  "OLIMPBET.kz",
  "Yajuego",
  "Bwin.ru",
  "unibet.nj",
  "BetAndYou",
  "Placard",
  "BetBoom",
  "Bilyoner",
  "PZBuk",
  "Sts.bet.com",
  "Sts.co.uk",
  "BETFAN",
  "MELbet",
  "Betano.br",
  "BetInAsia",
  "Fastbet",
  "Betsensation",
  "Betmaster",
  "BetPlanet",
  "10x10bet",
  "Soccabet",
  "Curebet",
  "Lasbet",
  "Betika.com.gh",
  "Circus",
  "Betway PT",
  "FEZbet",
  "Betway Africa Mozambique",
  "Rojabet",
  "Superbet.pl",
  "Superbet.ro",
  "Tennisi.kz",
  "BetFinal",
  "Solverde.pt",
  "bet365.ru",
  "Latribet",
  "Bwin.co",
  "MSport",
  "Chezacash",
  "GreatOdds",
  "GreatOdds.rs",
  "CasaPariurilor",
  "Fonbet.by",
  "bet365.nl",
  "efbet.it",
  "N1 Bet",
  "Favbet",
  "Golpas",
  "Ditobet",
  "Efbet RO",
  "Betring",
  "ErisBet365",
  "OlyBet.it",
  "VOBET",
  "Betera",
  "Unibetbe",
  "Unibetdk",
  "Unibetnl",
  "Unibetca",
  "Unibetro",
  "Unibetse",
  "Unibetuk",
  "Unibethu",
  "Unibetee",
  "Unibetau",
  "ErisBetterIt",
  "Winnermx",
  "Calientemx",
  "Novibet",
  "Betssonco",
  "BC.Game",
  "Starcasinoit",
  "Betssonno",
  "Alphabet",
  "Bwin Africa",
  "Pinup",
  "Suprabets",
  "Golden Palace",
  "Fonbet.ca",
  "Vincitu",
  "bet-at-home.de",
  "Mozzartbetke",
  "Mozzartbetrs",
  "Mozzartbetro",
  "Betssonmx",
  "Aposta Ganha",
  "sx.bet",
  "Expektse",
  "Expektdk",
  "Spinbookie",
  "Betclic.ci",
  "Stoiximan.cy",
  "Betano.cz",
  "Betano.de",
  "Betano.cl",
  "Betano.pe",
  "Betano.ec",
  "Betano.ng",
  "Betano.bg",
  "Ibet",
  "Betano.ca (Ontario)",
  "Betano.ca (rest of canada)",
  "Zebet",
  "VbetFR",
  "Betika Zambia",
  "LeoVegasPE",
  "BetMGM",
  "VbetUK",
  "Germania",
  "CoolbetLATAM",
  "PerformanceTest",
  "Winlinekz",
  "Winlineby",
  "Ubet",
  "PerformanceTestGo",
];

const urlRegex = /^(https?:\/\/)?([a-zA-Z0-9.-]+)(:[0-9]{1,5})?(\/.*)?$/;

const BookiesSchema = new Schema(
  {
    bookieName: { type: String, enum: bookies, required: true },
    URL: {
      type: String,
      required: true,
      validate: {
        validator: function (v) {
          return urlRegex.test(v);
        },
        message: props => `${props.value} is not a valid URL!`
      }
    },
  },
  { timestamps: true } 
);

module.exports = mongoose.model("Bookies", BookiesSchema);
